Automatically generate github access tokens
For increased productivity for developers, we shall get tokens
directly to our terminal instead of using their browsers.
This will make life easier for all of us.

diff --git a/gh-pages b/gh-pages
--- a/gh-pages
+++ b/gh-pages
@@ -22,9 +22,12 @@ command -v gh-pages > /dev/null 2>&1 && {
 ORIGIN="${ROOT}/gh-pages-lib"
 TEMPLATES="${ROOT}/gh-pages-templates"
 
+# templates
 GITBOOK_URL="https://github.com/GochoMugo/gh-pages-gitbook.git"
 JEKYLL_URL="https://github.com/GochoMugo/gh-pages-jekyll.git"
 
+# github access tokens
+SCOPES="[\"public_repo\"]"
 
 
 # utilities
@@ -55,27 +58,64 @@ case ${1} in
       log "please install this command using: gem install travis" 2
       exit 1
     }
-    if [ ! -e .travis/config.sh ]
+    CONFIG_FILE=".travis/config.sh"
+    if [ ! -e ${CONFIG_FILE} ]
     then
-      log "fill in these details" 0
-      read -p "    Repository Url: " REPO_URL
-      read -p "    Branch to Deploy to [gh-pages]: " BRANCH
-      read -p "    Output Directory [_out]: " DEST_DIR
-      read -p "    Github Username: " USER_NAME
-      read -p "    Email Address: " USER_EMAIL
-      read -p "    Github Access Token: " GH_TOKEN
-      [ ${BRANCH} ] || BRANCH="gh-pages"
-      [ ${DEST_DIR} ] || DEST_DIR="_out"
-      echo "REPO_URL=${REPO_URL}" >> .travis/config.sh
-      echo "BRANCH=${BRANCH}" >> .travis/config.sh
-      echo "DEST_DIR=${DEST_DIR}" >> .travis/config.sh
-      echo "USER_NAME=${USER_NAME}" >> .travis/config.sh
-      echo "USER_EMAIL=${USER_EMAIL}" >> .travis/config.sh
-      travis encrypt GH_TOKEN=${GH_TOKEN} --skip-version-check --add || {
-        log "failed!" 2
-        rm .travis/config.sh
+      log "please fill in these details" 0
+      BRANCH="gh-pages"
+      DEST_DIR="_out"
+      if [ -d .git ]
+      then
+        REPO_URL="$(git remote -v | grep -Ei 'origin.*push' | grep -Eio '[a-z]+://.* ')"
+        USER_NAME="$(git config user.name)"
+        USER_EMAIL="$(git config user.email)"
+      fi
+      read -p "    Repository Url [$REPO_URL]: " REPO_URL
+      read -p "    Branch to Deploy to [${BRANCH}]: " BRANCH
+      read -p "    Output Directory [${DEST_DIR}]: " DEST_DIR
+      read -p "    Github Username [${USER_NAME}]: " USER_NAME
+      read -p "    Email Address [${USER_EMAIL}]: " USER_EMAIL
+      if [ ! -e .token ]
+      then
+        read -p "    Github Password: " -s USER_PASS
+        echo
+        echo "    --- Please Wait ---"
+        echo
+        curl -s \
+          -u ${USER_NAME}:${USER_PASS} \
+          -X POST https://api.github.com/authorizations \
+          --data "{\"scopes\": ${SCOPES}, \
+            \"note\": \"gh-pages: ${REPO_URL}\"}" > .res
+        cat .res \
+          | grep -Ei "\"token\": " \
+          | grep -Eio ": \"[a-z0-9]+" \
+          | grep -Eio "[a-z0-9]+" > .token
+      fi
+      GH_TOKEN="$(cat .token)"
+      [ ${GH_TOKEN} ] || {
+        log "failed to generate an access token from Github" 2
+        ask_bool "show error response" "n" && {
+          cat .res
+          rm .res .token
+        }
         exit 1
       }
+      rm .res
+      echo "REPO_URL=${REPO_URL}" >> ${CONFIG_FILE}
+      echo "BRANCH=${BRANCH}" >> ${CONFIG_FILE}
+      echo "DEST_DIR=${DEST_DIR}" >> ${CONFIG_FILE}
+      echo "USER_NAME=${USER_NAME}" >> ${CONFIG_FILE}
+      echo "USER_EMAIL=${USER_EMAIL}" >> ${CONFIG_FILE}
+      travis encrypt GH_TOKEN=${GH_TOKEN} \
+        --skip-version-check --add || {
+        log "failed encrypting with travis!" 2
+        log "!! note that your github access token has been saved to .token" 2
+        log "!! ensure you do NOT commit this file" 2
+        log "!! RETRY! On success, .token will be auto-deleted" 2
+        rm ${CONFIG_FILE}
+        exit 1
+      }
+      rm .token
       log "finished!" 1
     fi
   ;;
@@ -142,8 +182,6 @@ case ${1} in
     echo " More Information:"
     echo "    You can easily install recommended templates using"
     echo "     ⇒ gh-pages recommended-templates"
-    echo "    Head over to https://github.com/settings/tokens to"
-    echo "     generate new tokens"
     echo
   ;;
 esac
